/* Build the `#d=` links for the decks shipped with the site.
 *
 * A deck travels inside the link: the JSON is compressed with lz-string and packed into the
 * hash, which is what core/shell.js reads at boot. The landing could do that itself by fetching
 * the JSON, but fetch() is refused on file://, so the two hashes are built here instead and
 * written beside the decks as data (links.json) and as a plain global (links.js) the landing
 * can load with a <script> tag on any protocol.
 *
 * Run from the repo root, after core/ has been synced:
 *     node scripts/build-links.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(import.meta.url);
const LZString = require(resolve(ROOT, "core/vendor/lz-string.min.js"));

const DECKS = ["how-own-words-works", "claude-code-in-30-questions"];

const links = {};
for (const name of DECKS) {
  const path = resolve(ROOT, "decks", name + ".json");
  const deck = JSON.parse(readFileSync(path, "utf8"));
  // Re-stringified rather than passed through, so the hash carries exactly the bytes the
  // engine will JSON.parse back out of it and nothing of the file's formatting.
  const hash = LZString.compressToEncodedURIComponent(JSON.stringify(deck));
  const back = JSON.parse(LZString.decompressFromEncodedURIComponent(hash));
  if (back.key !== deck.key) throw new Error("round trip lost the key of " + name);
  links[name] = hash;
  console.log(name + ": " + hash.length + " chars");
}

writeFileSync(resolve(ROOT, "decks/links.json"), JSON.stringify(links, null, 2) + "\n");
writeFileSync(
  resolve(ROOT, "decks/links.js"),
  "/* Generated by scripts/build-links.mjs. Do not edit. */\n" +
    "window.OWN_WORDS_LINKS = " + JSON.stringify(links, null, 2) + ";\n"
);
console.log("wrote decks/links.json and decks/links.js");
